services:
  api-gateway:
    build:
      target: runner
    develop: !reset []
  user-service:
    build:
      target: runner
    develop: !reset []
  client:
    build:
      target: runner
    ports:
      - "8080:8080"
    develop: !reset []
